import type { CardEntry } from '../types/models'

export type OnlinePlayerId = 'A' | 'B'
export type OnlineRoomPhase = 'lobby' | 'playing' | 'over'

export interface OnlineCardInput {
  key: string
  number: number
  imageName: string
  imagePath?: string
  workName: string
  songs: Array<{
    fileName: string
    displayName: string
    sourcePath?: string
  }>
}

export interface OnlineCardView {
  key: string
  number: number
  imageName: string
  workName: string
}

export interface OnlinePlayerView {
  id: OnlinePlayerId
  nickname: string
  connected: boolean
  ready: boolean
  score: number
  correctClaims: number
  network: OnlineNetworkView
}

export interface OnlineNetworkView {
  rttMs: number | null
  jitterMs: number | null
  samples: number
}

export type OnlineFairnessStatus = 'measuring' | 'ready' | 'unfair'

export interface OnlineFairnessView {
  status: OnlineFairnessStatus
  canStart: boolean
  rttGapMs: number | null
  jitterGapMs: number | null
  maxJitterMs: number | null
  message: string
}

export interface OnlineRoomView {
  code: string
  name: string
  packageId: string
  deckName: string
  you: OnlinePlayerId
  phase: OnlineRoomPhase
  players: Record<OnlinePlayerId, OnlinePlayerView | null>
  cards: OnlineCardView[]
  remainingCardKeys: string[]
  roundNo: number
  totalRounds: number
  fairness: OnlineFairnessView
}

export interface OnlineRoomSummary {
  code: string
  name: string
  deckName: string
  players: number
  status: 'waiting' | 'full' | 'playing'
}

export type OnlineClientMessage =
  | { t: 'hello'; resumeToken?: string }
  | { t: 'listRooms' }
  | {
      t: 'createRoom'
      nickname: string
      name: string
      packageId: string
      deckName: string
      cards: OnlineCardInput[]
    }
  | { t: 'joinRoom'; code: string; nickname: string }
  | { t: 'ready'; ready: boolean }
  | { t: 'claim'; roundNo: number; cardKey: string; clientAt: number }
  | { t: 'leaveRoom' }
  | { t: 'ping'; clientAt: number }

export interface OnlineRoundStart {
  t: 'roundStart'
  roundNo: number
  startAtServerTime: number
  windowMs: number
  audioUrl: string
}

export interface OnlineRoundResult {
  t: 'roundResult'
  roundNo: number
  cardKey: string
  winner: OnlinePlayerId | null
  reason: 'claimed' | 'timeout'
  song: { displayName: string; fileName: string }
  scores: Record<OnlinePlayerId, number>
  remainingCardKeys: string[]
  nextRoundAtServerTime: number | null
}

export type OnlineServerMessage =
  | { t: 'welcome'; resumed: boolean; resumeToken?: string }
  | { t: 'room'; room: OnlineRoomView }
  | { t: 'roomList'; rooms: OnlineRoomSummary[] }
  | OnlineRoundStart
  | { t: 'claimFeedback'; playerId: OnlinePlayerId; cardKey: string; correct: boolean }
  | OnlineRoundResult
  | {
      t: 'matchOver'
      winner: OnlinePlayerId | null
      scores: Record<OnlinePlayerId, number>
      rounds: number
    }
  | { t: 'peer'; playerId: OnlinePlayerId; connected: boolean }
  | { t: 'pong'; clientAt: number; serverAt: number }
  | { t: 'error'; code: string; message: string }

/**
 * A card id generated by IndexedDB is intentionally local and random. The
 * source path gives two browsers importing the same server package a stable
 * identity, while the remaining fields keep hand-created/exported decks usable.
 */
export function onlineCardKey(card: Pick<CardEntry, 'number' | 'imageName' | 'imagePath' | 'workName'>): string {
  const image = card.imagePath?.trim() || card.imageName.trim()
  return [String(card.number), image, card.workName.trim()].join('|')
}

export function toOnlineCardInput(card: CardEntry): OnlineCardInput {
  return {
    key: onlineCardKey(card),
    number: card.number,
    imageName: card.imageName,
    ...(card.imagePath ? { imagePath: card.imagePath } : {}),
    workName: card.workName,
    songs: card.songs.map((song) => ({
      fileName: song.fileName,
      displayName: song.displayName,
      ...(song.sourcePath ? { sourcePath: song.sourcePath } : {}),
    })),
  }
}

export function onlineCardViewKey(card: OnlineCardView): string {
  return card.key
}
