export const MIN_CANDIDATE_CARDS = 60
export const MAX_CANDIDATE_CARDS = 500
export const DEFAULT_CANDIDATE_CARDS = 60
export const DRAFT_SELECTION_SIZE = 30
export const BAN_SIZE = 5
export const MAX_HAND_SLOTS = 33
export const REST_AUDIO_VOLUME = 0.28
export const ONLINE_VOLUME_STORAGE_KEY = 'karuta-online-volume'
export const DEFAULT_ONLINE_VOLUME = 0.8
export const EMPTY_CARD_KEYS: string[] = []
export const COUNTDOWN_EARLY_WAKE_MS = 24
export const MEDIA_READY_TIMEOUT_MS = 15_000
export const MATCH_AUDIO_CONCURRENCY = 4
export const BATTLE_STYLE_STORAGE_KEY = 'karuta-online-battle-style'
export const BATTLE_ANIMATION_DURATION_MS = 2_400
export const BATTLE_ANIMATION_DEDUPE_WINDOW_MS = 1_200
export const BATTLE_ANIMATION_LOCAL_ECHO_WINDOW_MS = 8_000
export const MAX_BATTLE_ANIMATION_QUEUE = 8
